version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: ghcr.io/bcgov/sso:26.0.7-build.1
    depends_on:
    - postgres
    ports:
    - 8080:8080
    command: start-dev
    environment:
      DB_POSTGRESQL_SERVICE_HOST: postgres
      DB_POSTGRESQL_SERVICE_PORT: 5433
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL: jdbc:postgresql://postgres:5433/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      DB_MIN_POOL_SIZE: 1
      DB_MAX_POOL_SIZE: 5
      JGROUPS_CLUSTER_PASSWORD: password
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.impersonation=disabled -Djboss.persistent.log.dir=/var/log/eap -Djgroups.dns.query=sso-keycloak-ping.c6af30-test.svc.cluster.local
      KC_HTTP_RELATIVE_PATH: /auth
      DB_JNDI: java:jboss/datasources/KeycloakDS
      DB_SERVICE_PREFIX_MAPPING: db-postgresql=DB
      TX_DATABASE_PREFIX_MAPPING: db-postgresql=DB
      TZ: America/Vancouver
    volumes:
    - logs_data:/var/log/eap

  postgres:
    image: docker.io/postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    tty: true
    ports:
    - 5433:5433
    command: -p 5433
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  logs_data:
    driver: local
