name: Setup Terraform
description: Setup SSO Terraform workspace

inputs:
  context:
    description: Terraform workspace directory
    required: false
    default: .
  tf-version:
    description: Terraform version
    required: true
  tf-s3-bucket:
    description: Terraform S3 Remote backend bucket name
    required: true
  tf-s3-bucket-key:
    description: Terraform S3 Remote backend bucket key (path)
    required: true
  tf-aws-deploy-role-arn:
    description: Amazon Resource Name (ARN) of the IAM Role to access Terraform S3 Bucket
    required: true
  kc-provider-version:
    description: Keycloak Terraform provider version
    required: true
  kc-url:
    description: Keycloak url
    required: true
  kc-username:
    description: Keycloak admin username
    required: true
  kc-password:
    description: Keycloak admin password
    required: true
  siteminder-signing-certificate:
    description: Siteminder signing certificate
    required: false
    default: ''
  azureidir-tenant-id:
    description: Azure IDIR Tenant ID
    required: false
    default: ''
  azureidir-client-id:
    description: Azure IDIR Client ID
    required: false
    default: ''
  azureidir-client-secret:
    description: Azure IDIR Client Secret
    required: false
    default: ''
  github-client-id:
    description: GitHub Client ID
    required: false
    default: ''
  github-client-secret:
    description: GitHub Client Secret
    required: false
    default: ''
  digitalcredential-client-id:
    description: Digital Credential Client ID
    required: false
    default: ''
  digitalcredential-client-secret:
    description: Digital Credential Client Secret
    required: false
    default: ''
  otp-client-id:
    description: OTP Client ID
    required: false
    default: ''
  otp-client-secret:
    description: OTP Client Secret
    required: false
    default: ''
  ppid-client-id:
    description: PPID API Client ID
    required: false
    default: ''
  ppid-client-secret:
    description: PPID API Client Secret
    required: false
    default: ''
  plan:
    description: Whether to run Terraform plan
    required: false
    default: 'false'
  apply:
    description: Whether to run Terraform apply
    required: false
    default: 'false'
  state-rm:
    description: Resource address to remove the state
    required: false
    default: ''
  tf-modules-cache-key:
    description: Terraform Modules Cache Key
    required: false
    default: sso

outputs:
  init:
    description: Terraform init outcome
    value: ${{ steps.init.outcome }}
  fmt:
    description: Terraform fmt outcome
    value: ${{ steps.fmt.outcome }}
  plan:
    description: Terraform plan outcome
    value: ${{ steps.plan.outcome }}
  apply:
    description: Terraform apply outcome
    value: ${{ steps.apply.outcome }}

runs:
  using: composite
  steps:
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: ${{ inputs.tf-version }}

  - name: Terraform Format
    id: fmt
    run: terraform fmt -check
    shell: bash
    working-directory: ${{ inputs.context }}

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.tf-aws-deploy-role-arn }}
      aws-region: ca-central-1

  - name: Terraform Variables
    run: |
      cat >"config.tf" <<EOF
      terraform {
        backend "s3" {
          bucket         = "${{ inputs.tf-s3-bucket }}"
          key            = "${{ inputs.tf-s3-bucket-key }}"
          region         = "ca-central-1"
          use_lockfile     = true
        }
        required_providers {
          keycloak = {
            source  = "keycloak/keycloak"
            version = "${{ inputs.kc-provider-version }}"
          }
        }
      }
      EOF

      cat >"ci.auto.tfvars" <<'EOF'
      keycloak_url="${{ inputs.kc-url }}"
      username="${{ inputs.kc-username }}"
      password="${{ inputs.kc-password }}"
      siteminder_signing_certificate="${{ inputs.siteminder-signing-certificate }}"

      azureidir_tenant_id="${{ inputs.azureidir-tenant-id }}"
      azureidir_client_id="${{ inputs.azureidir-client-id }}"
      azureidir_client_secret="${{ inputs.azureidir-client-secret }}"
      github_client_id="${{ inputs.github-client-id }}"
      github_client_secret="${{ inputs.github-client-secret }}"
      digitalcredential_client_id="${{ inputs.digitalcredential-client-id }}"
      digitalcredential_client_secret="${{ inputs.digitalcredential-client-secret }}"
      otp_client_id="${{ inputs.otp-client-id }}"
      otp_client_secret="${{ inputs.otp-client-secret }}"
      ppid_client_id="${{ inputs.ppid-client-id }}"
      ppid_client_secret="${{ inputs.ppid-client-secret }}"

      EOF
    shell: bash
    working-directory: ${{ inputs.context }}

  - name: Cache Terraform Modules
    id: cache-tf-modules
    uses: actions/cache@v4
    with:
      path: ${{ inputs.context }}/.terraform
      key: ${{ runner.os }}-terraform-${{ inputs.tf-modules-cache-key }}

  - name: Terraform Init
    id: init
    run: terraform init -reconfigure
    shell: bash
    working-directory: ${{ inputs.context }}

  - name: Terraform Plan
    if: inputs.plan == 'true'
    id: plan
    run: terraform plan -no-color
    shell: bash
    working-directory: ${{ inputs.context }}

  - name: Terraform Apply
    if: inputs.apply == 'true'
    id: apply
    run: terraform apply -auto-approve
    shell: bash
    working-directory: ${{ inputs.context }}

        # see https://www.terraform.io/cli/commands/state/rm
  - name: Terraform State Remove
    if: inputs.state-rm != ''
    id: remove
    run: |
      address=${{ inputs.state-rm }}
      echo "$address"
      terraform state rm "$address"
    shell: bash
    working-directory: ${{ inputs.context }}
