name: Migraaaate secrets to openshift

on: workflow_dispatch

env:
  TF_VERSION: 1.11.0

jobs:
  terraform:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:

    - uses: actions/checkout@v2

    - name: Login Openshift Gold
      uses: ./.github/actions/oc-login
      with:
        namespace: eb75ad-tools
        oc-server-gold: ${{ secrets.OPENSHIFT_SERVER_GOLD }}
        oc-token-gold: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}

    - name: Create keycloak-terraform-secrets in OpenShift
      run: |
        oc create secret generic keycloak-terraform-secrets \
          --from-literal=SSO_AWS_GH_ACTIONS_DEPLOYER_SANDBOX="${{ secrets.SSO_AWS_GH_ACTIONS_DEPLOYER_SANDBOX }}" \
          --from-literal=SSO_AWS_GH_ACTIONS_DEPLOYER_PRODUCTION="${{ secrets.SSO_AWS_GH_ACTIONS_DEPLOYER_PRODUCTION }}" \
          --from-literal=KEYCLOAK_V2_DEV_USERNAME_SANDBOX="${{ secrets.KEYCLOAK_V2_DEV_USERNAME_SANDBOX }}" \
          --from-literal=KEYCLOAK_V2_DEV_PASSWORD_SANDBOX="${{ secrets.KEYCLOAK_V2_DEV_PASSWORD_SANDBOX }}" \
          --from-literal=DEV_AZUREIDIR_TENANT_ID="${{ secrets.DEV_AZUREIDIR_TENANT_ID }}" \
          --from-literal=DEV_AZUREIDIR_CLIENT_ID_SANDBOX="${{ secrets.DEV_AZUREIDIR_CLIENT_ID_SANDBOX }}" \
          --from-literal=DEV_AZUREIDIR_CLIENT_SECRET_SANDBOX="${{ secrets.DEV_AZUREIDIR_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=DEV_GITHUB_CLIENT_ID_SANDBOX="${{ secrets.DEV_GITHUB_CLIENT_ID_SANDBOX }}" \
          --from-literal=DEV_GITHUB_CLIENT_SECRET_SANDBOX="${{ secrets.DEV_GITHUB_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=DEV_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX="${{ secrets.DEV_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX }}" \
          --from-literal=DEV_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX="${{ secrets.DEV_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=DEV_OTP_CLIENT_ID_SANDBOX="${{ secrets.DEV_OTP_CLIENT_ID_SANDBOX }}" \
          --from-literal=DEV_OTP_CLIENT_SECRET_SANDBOX="${{ secrets.DEV_OTP_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=DEV_PPID_CLIENT_ID_SANDBOX="${{ secrets.DEV_PPID_CLIENT_ID_SANDBOX }}" \
          --from-literal=DEV_PPID_CLIENT_SECRET_SANDBOX="${{ secrets.DEV_PPID_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=KEYCLOAK_V2_DEV_USERNAME_PRODUCTION="${{ secrets.KEYCLOAK_V2_DEV_USERNAME_PRODUCTION }}" \
          --from-literal=KEYCLOAK_V2_DEV_PASSWORD_PRODUCTION="${{ secrets.KEYCLOAK_V2_DEV_PASSWORD_PRODUCTION }}" \
          --from-literal=DEV_AZUREIDIR_CLIENT_ID_PRODUCTION="${{ secrets.DEV_AZUREIDIR_CLIENT_ID_PRODUCTION }}" \
          --from-literal=DEV_AZUREIDIR_CLIENT_SECRET_PRODUCTION="${{ secrets.DEV_AZUREIDIR_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=DEV_GITHUB_CLIENT_ID_PRODUCTION="${{ secrets.DEV_GITHUB_CLIENT_ID_PRODUCTION }}" \
          --from-literal=DEV_GITHUB_CLIENT_SECRET_PRODUCTION="${{ secrets.DEV_GITHUB_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=DEV_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION="${{ secrets.DEV_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION }}" \
          --from-literal=DEV_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION="${{ secrets.DEV_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=DEV_OTP_CLIENT_ID_PRODUCTION="${{ secrets.DEV_OTP_CLIENT_ID_PRODUCTION }}" \
          --from-literal=DEV_OTP_CLIENT_SECRET_PRODUCTION="${{ secrets.DEV_OTP_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=DEV_PPID_CLIENT_ID_PRODUCTION="${{ secrets.DEV_PPID_CLIENT_ID_PRODUCTION }}" \
          --from-literal=DEV_PPID_CLIENT_SECRET_PRODUCTION="${{ secrets.DEV_PPID_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=KEYCLOAK_V2_TEST_USERNAME_SANDBOX="${{ secrets.KEYCLOAK_V2_TEST_USERNAME_SANDBOX }}" \
          --from-literal=KEYCLOAK_V2_TEST_PASSWORD_SANDBOX="${{ secrets.KEYCLOAK_V2_TEST_PASSWORD_SANDBOX }}" \
          --from-literal=TEST_AZUREIDIR_TENANT_ID="${{ secrets.TEST_AZUREIDIR_TENANT_ID }}" \
          --from-literal=TEST_AZUREIDIR_CLIENT_ID_SANDBOX="${{ secrets.TEST_AZUREIDIR_CLIENT_ID_SANDBOX }}" \
          --from-literal=TEST_AZUREIDIR_CLIENT_SECRET_SANDBOX="${{ secrets.TEST_AZUREIDIR_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=TEST_GITHUB_CLIENT_ID_SANDBOX="${{ secrets.TEST_GITHUB_CLIENT_ID_SANDBOX }}" \
          --from-literal=TEST_GITHUB_CLIENT_SECRET_SANDBOX="${{ secrets.TEST_GITHUB_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=TEST_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX="${{ secrets.TEST_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX }}" \
          --from-literal=TEST_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX="${{ secrets.TEST_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=TEST_OTP_CLIENT_ID_SANDBOX="${{ secrets.TEST_OTP_CLIENT_ID_SANDBOX }}" \
          --from-literal=TEST_OTP_CLIENT_SECRET_SANDBOX="${{ secrets.TEST_OTP_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=TEST_PPID_CLIENT_ID_SANDBOX="${{ secrets.TEST_PPID_CLIENT_ID_SANDBOX }}" \
          --from-literal=TEST_PPID_CLIENT_SECRET_SANDBOX="${{ secrets.TEST_PPID_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=KEYCLOAK_V2_TEST_USERNAME_PRODUCTION="${{ secrets.KEYCLOAK_V2_TEST_USERNAME_PRODUCTION }}" \
          --from-literal=KEYCLOAK_V2_TEST_PASSWORD_PRODUCTION="${{ secrets.KEYCLOAK_V2_TEST_PASSWORD_PRODUCTION }}" \
          --from-literal=TEST_AZUREIDIR_CLIENT_ID_PRODUCTION="${{ secrets.TEST_AZUREIDIR_CLIENT_ID_PRODUCTION }}" \
          --from-literal=TEST_AZUREIDIR_CLIENT_SECRET_PRODUCTION="${{ secrets.TEST_AZUREIDIR_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=TEST_GITHUB_CLIENT_ID_PRODUCTION="${{ secrets.TEST_GITHUB_CLIENT_ID_PRODUCTION }}" \
          --from-literal=TEST_GITHUB_CLIENT_SECRET_PRODUCTION="${{ secrets.TEST_GITHUB_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=TEST_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION="${{ secrets.TEST_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION }}" \
          --from-literal=TEST_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION="${{ secrets.TEST_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=TEST_OTP_CLIENT_ID_PRODUCTION="${{ secrets.TEST_OTP_CLIENT_ID_PRODUCTION }}" \
          --from-literal=TEST_OTP_CLIENT_SECRET_PRODUCTION="${{ secrets.TEST_OTP_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=TEST_PPID_CLIENT_ID_PRODUCTION="${{ secrets.TEST_PPID_CLIENT_ID_PRODUCTION }}" \
          --from-literal=TEST_PPID_CLIENT_SECRET_PRODUCTION="${{ secrets.TEST_PPID_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=KEYCLOAK_V2_PROD_USERNAME_SANDBOX="${{ secrets.KEYCLOAK_V2_PROD_USERNAME_SANDBOX }}" \
          --from-literal=KEYCLOAK_V2_PROD_PASSWORD_SANDBOX="${{ secrets.KEYCLOAK_V2_PROD_PASSWORD_SANDBOX }}" \
          --from-literal=PROD_AZUREIDIR_TENANT_ID="${{ secrets.PROD_AZUREIDIR_TENANT_ID }}" \
          --from-literal=PROD_AZUREIDIR_CLIENT_ID_SANDBOX="${{ secrets.PROD_AZUREIDIR_CLIENT_ID_SANDBOX }}" \
          --from-literal=PROD_AZUREIDIR_CLIENT_SECRET_SANDBOX="${{ secrets.PROD_AZUREIDIR_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=PROD_GITHUB_CLIENT_ID_SANDBOX="${{ secrets.PROD_GITHUB_CLIENT_ID_SANDBOX }}" \
          --from-literal=PROD_GITHUB_CLIENT_SECRET_SANDBOX="${{ secrets.PROD_GITHUB_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=PROD_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX="${{ secrets.PROD_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX }}" \
          --from-literal=PROD_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX="${{ secrets.PROD_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=PROD_OTP_CLIENT_ID_SANDBOX="${{ secrets.PROD_OTP_CLIENT_ID_SANDBOX }}" \
          --from-literal=PROD_OTP_CLIENT_SECRET_SANDBOX="${{ secrets.PROD_OTP_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=PROD_PPID_CLIENT_ID_SANDBOX="${{ secrets.PROD_PPID_CLIENT_ID_SANDBOX }}" \
          --from-literal=PROD_PPID_CLIENT_SECRET_SANDBOX="${{ secrets.PROD_PPID_CLIENT_SECRET_SANDBOX }}" \
          --from-literal=KEYCLOAK_V2_PROD_USERNAME_PRODUCTION="${{ secrets.KEYCLOAK_V2_PROD_USERNAME_PRODUCTION }}" \
          --from-literal=KEYCLOAK_V2_PROD_PASSWORD_PRODUCTION="${{ secrets.KEYCLOAK_V2_PROD_PASSWORD_PRODUCTION }}" \
          --from-literal=PROD_AZUREIDIR_CLIENT_ID_PRODUCTION="${{ secrets.PROD_AZUREIDIR_CLIENT_ID_PRODUCTION }}" \
          --from-literal=PROD_AZUREIDIR_CLIENT_SECRET_PRODUCTION="${{ secrets.PROD_AZUREIDIR_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=PROD_GITHUB_CLIENT_ID_PRODUCTION="${{ secrets.PROD_GITHUB_CLIENT_ID_PRODUCTION }}" \
          --from-literal=PROD_GITHUB_CLIENT_SECRET_PRODUCTION="${{ secrets.PROD_GITHUB_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=PROD_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION="${{ secrets.PROD_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION }}" \
          --from-literal=PROD_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION="${{ secrets.PROD_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=PROD_OTP_CLIENT_ID_PRODUCTION="${{ secrets.PROD_OTP_CLIENT_ID_PRODUCTION }}" \
          --from-literal=PROD_OTP_CLIENT_SECRET_PRODUCTION="${{ secrets.PROD_OTP_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=PROD_PPID_CLIENT_ID_PRODUCTION="${{ secrets.PROD_PPID_CLIENT_ID_PRODUCTION }}" \
          --from-literal=PROD_PPID_CLIENT_SECRET_PRODUCTION="${{ secrets.PROD_PPID_CLIENT_SECRET_PRODUCTION }}" \
          --from-literal=TEST_SITEMINDER_SIGNING_CERTIFICATE="${{ secrets.TEST_SITEMINDER_SIGNING_CERTIFICATE }}" \
          --from-literal=PROD_SITEMINDER_SIGNING_CERTIFICATE="${{ secrets.PROD_SITEMINDER_SIGNING_CERTIFICATE }}" \
          --dry-run=client -o yaml -n eb75ad-tools | oc apply -f -
# SSO_AWS_GH_ACTIONS_DEPLOYER_SANDBOX
# SSO_AWS_GH_ACTIONS_DEPLOYER_PRODUCTION

# KEYCLOAK_V2_DEV_USERNAME_SANDBOX
# KEYCLOAK_V2_DEV_PASSWORD_SANDBOX
# DEV_AZUREIDIR_TENANT_ID
# DEV_AZUREIDIR_CLIENT_ID_SANDBOX
# DEV_AZUREIDIR_CLIENT_SECRET_SANDBOX
# DEV_GITHUB_CLIENT_ID_SANDBOX
# DEV_GITHUB_CLIENT_SECRET_SANDBOX
# DEV_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX
# DEV_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX
# DEV_OTP_CLIENT_ID_SANDBOX
# DEV_OTP_CLIENT_SECRET_SANDBOX
# DEV_PPID_CLIENT_ID_SANDBOX
# DEV_PPID_CLIENT_SECRET_SANDBOX

# KEYCLOAK_V2_DEV_USERNAME_PRODUCTION
# KEYCLOAK_V2_DEV_PASSWORD_PRODUCTION
# DEV_AZUREIDIR_TENANT_ID
# DEV_AZUREIDIR_CLIENT_ID_PRODUCTION
# DEV_AZUREIDIR_CLIENT_SECRET_PRODUCTION
# DEV_GITHUB_CLIENT_ID_PRODUCTION
# DEV_GITHUB_CLIENT_SECRET_PRODUCTION
# DEV_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION
# DEV_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION
# DEV_OTP_CLIENT_ID_PRODUCTION
# DEV_OTP_CLIENT_SECRET_PRODUCTION
# DEV_PPID_CLIENT_ID_PRODUCTION
# DEV_PPID_CLIENT_SECRET_PRODUCTION


# KEYCLOAK_V2_TEST_USERNAME_SANDBOX
# KEYCLOAK_V2_TEST_PASSWORD_SANDBOX
# TEST_AZUREIDIR_TENANT_ID
# TEST_AZUREIDIR_CLIENT_ID_SANDBOX
# TEST_AZUREIDIR_CLIENT_SECRET_SANDBOX
# TEST_GITHUB_CLIENT_ID_SANDBOX
# TEST_GITHUB_CLIENT_SECRET_SANDBOX
# TEST_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX
# TEST_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX
# TEST_OTP_CLIENT_ID_SANDBOX
# TEST_OTP_CLIENT_SECRET_SANDBOX
# TEST_PPID_CLIENT_ID_SANDBOX
# TEST_PPID_CLIENT_SECRET_SANDBOX

# KEYCLOAK_V2_TEST_USERNAME_PRODUCTION
# KEYCLOAK_V2_TEST_PASSWORD_PRODUCTION
# TEST_AZUREIDIR_TENANT_ID
# TEST_AZUREIDIR_CLIENT_ID_PRODUCTION
# TEST_AZUREIDIR_CLIENT_SECRET_PRODUCTION
# TEST_GITHUB_CLIENT_ID_PRODUCTION
# TEST_GITHUB_CLIENT_SECRET_PRODUCTION
# TEST_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION
# TEST_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION
# TEST_OTP_CLIENT_ID_PRODUCTION
# TEST_OTP_CLIENT_SECRET_PRODUCTION
# TEST_PPID_CLIENT_ID_PRODUCTION
# TEST_PPID_CLIENT_SECRET_PRODUCTION

# KEYCLOAK_V2_PROD_USERNAME_SANDBOX
# KEYCLOAK_V2_PROD_PASSWORD_SANDBOX
# PROD_AZUREIDIR_TENANT_ID
# PROD_AZUREIDIR_CLIENT_ID_SANDBOX
# PROD_AZUREIDIR_CLIENT_SECRET_SANDBOX
# PROD_GITHUB_CLIENT_ID_SANDBOX
# PROD_GITHUB_CLIENT_SECRET_SANDBOX
# PROD_DIGITALCREDENTIAL_CLIENT_ID_SANDBOX
# PROD_DIGITALCREDENTIAL_CLIENT_SECRET_SANDBOX
# PROD_OTP_CLIENT_ID_SANDBOX
# PROD_OTP_CLIENT_SECRET_SANDBOX
# PROD_PPID_CLIENT_ID_SANDBOX
# PROD_PPID_CLIENT_SECRET_SANDBOX

# KEYCLOAK_V2_PROD_USERNAME_PRODUCTION
# KEYCLOAK_V2_PROD_PASSWORD_PRODUCTION
# PROD_AZUREIDIR_TENANT_ID
# PROD_AZUREIDIR_CLIENT_ID_PRODUCTION
# PROD_AZUREIDIR_CLIENT_SECRET_PRODUCTION
# PROD_GITHUB_CLIENT_ID_PRODUCTION
# PROD_GITHUB_CLIENT_SECRET_PRODUCTION
# PROD_DIGITALCREDENTIAL_CLIENT_ID_PRODUCTION
# PROD_DIGITALCREDENTIAL_CLIENT_SECRET_PRODUCTION
# PROD_OTP_CLIENT_ID_PRODUCTION
# PROD_OTP_CLIENT_SECRET_PRODUCTION
# PROD_PPID_CLIENT_ID_PRODUCTION
# PROD_PPID_CLIENT_SECRET_PRODUCTION

# TEST_SITEMINDER_SIGNING_CERTIFICATE
# PROD_SITEMINDER_SIGNING_CERTIFICATE
