name: Check Code/Commit Conventions

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: hmarr/debug-action@v3
    - uses: actions/checkout@v4

    - name: Get PR
      id: pr
      run: |
        pr=$(curl ${{ github.event.pull_request._links.self.href }})
        labels=$(jq ".labels" <<< "$pr")
        botLabel=$(jq -c '.[] | select(.name | contains("auto_generated")).name' <<< "$labels")
        echo "{count}={$count}" >> $GITHUB_OUTPUT

    - name: Install asdf requirements
      run: |
        sudo apt-get install -y libssl-dev libreadline-dev uuid-dev
    - name: Install asdf
      uses: asdf-vm/actions/setup@v3
    - name: Cache tools
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.asdf
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
    - name: Install required tools
      run: |
        cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin add || true
        asdf plugin update --all
        asdf install
        asdf reshim


    - name: Rerun Pre-Commit Hooks on CI
      if: steps.pr.outputs.botLabel != '"auto_generated"'
      run: pre-commit run --color=always --show-diff-on-failure --all-files

  commitlint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v5
