name: Check Code/Commit Conventions

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Get PR
        id: pr
        run: |
          pr=$(curl ${{ github.event.pull_request._links.self.href }})
          labels=$(jq ".labels" <<< "$pr")
          botLabel=$(jq -c '.[] | select(.name | contains("auto_generated")).name' <<< "$labels")
          echo "::set-output name=botLabel::$botLabel"

      - name: Setup Tools
        if: steps.pr.outputs.botLabel != '"auto_generated"'
        uses: bcgov/sso-requests-actions/actions/setup-tools@v0.34.0

      - name: Rerun Pre-Commit Hooks on CI
        if: steps.pr.outputs.botLabel != '"auto_generated"'
        run: pre-commit run --color=always --show-diff-on-failure --all-files

  commitlint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
