name: Check Code/Commit Conventions

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2

      - name: Get PR
        id: pr
        run: |
          pr=$(curl ${{ github.event.pull_request._links.self.href }})
          labels=$(jq ".labels" <<< "$pr")
          botLabel=$(jq -c '.[] | select(.name | contains("auto_generated")).name' <<< "$labels")
          echo "::set-output name=botLabel::$botLabel"

      - name: Install asdf
        if: steps.pr.outputs.botLabel != '"auto_generated"'
        uses: asdf-vm/actions/setup@v1

      - name: Cache tools
        if: steps.pr.outputs.botLabel != '"auto_generated"'
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.asdf
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Install required tools
        if: steps.pr.outputs.botLabel != '"auto_generated"'
        run: |
          cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
          asdf plugin-update --all
          asdf install
          asdf reshim

      - name: Rerun Pre-Commit Hooks on CI
        if: steps.pr.outputs.botLabel != '"auto_generated"'
        run: |
          pip install -r requirements.txt
          asdf reshim
          pre-commit run --color=always --show-diff-on-failure --all-files

  commitlint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
