name: Terraform V2 Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: env to deploy
        type: choice
        options: [dev, test, prod]
        default: dev
      staging-env:
        description: production vs sandbox evironment
        type: choice
        options: [sandbox, production]
        default: sandbox

env:
  TF_VERSION: 1.11.0

jobs:
  terraform:
    runs-on: ubuntu-24.04
    environment:
      name: ${{inputs.staging-env}}-${{ inputs.environment }}
      deployment: false
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      # - uses: hmarr/debug-action@cd1afbd7852b7ad7b1b7a9a1b03efebd3b0a1820 #v2
    - name: Fail if not main or dev
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'
      run: |
        echo "This workflow only runs on main or dev branches."
        exit 1

    - name: Fail if not using main for production environment or dev for sandbox
      if: (github.ref == 'refs/heads/main' && inputs.staging-env != 'production') || (github.ref == 'refs/heads/dev' && inputs.staging-env != 'sandbox')
      run: |
        echo "You have to use dev branch for sandbox and main branch for production deployments"
        exit 1

    - name: Set common variables
      run: echo "UPPER_ENV=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV

    - name: Set dev branch environment to SANDBOX
      if: ${{ inputs.staging-env == 'sandbox' && github.ref == 'refs/heads/dev' }}
      run: |
        echo "KEYCLOAK_V2_DEV_URL=https://dev.sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_TEST_URL=https://test.sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_PROD_URL=https://sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "PROJECT_SUFFIX=_SANDBOX" >> $GITHUB_ENV
        echo "SITEMINDER_PROJECT=TEST" >> $GITHUB_ENV
        echo "TF_S3_BUCKET=b46814-dev-keycloak" >> $GITHUB_ENV
        echo "TF_VAR_siteminder_single_sign_on_service_url=https://sfstest7.gov.bc.ca/affwebservices/public/saml2sso" >> $GITHUB_ENV
        echo "TF_VAR_github_org=bcgov-sso" >> $GITHUB_ENV
        echo "TF_VAR_bcsc_environment=sit" >> $GITHUB_ENV


        INPUT_ENV="${{ inputs.environment }}"

        if [ "$INPUT_ENV" = "dev" ]; then
          echo "TF_VAR_saml_entity_id_url=https://dev.sandbox.loginproxy.gov.bc.ca/auth/realms/"  >> $GITHUB_ENV
          echo "TF_VAR_otp_provider_url=https://dev.sandbox.otp.loginproxy.gov.bc.ca" >> $GITHUB_ENV
          echo "TF_VAR_otp_provider_id=oidc-client-home" >> $GITHUB_ENV
          echo "TF_VAR_otp_forward_parameters=client_home_url" >> $GITHUB_ENV

        elif [ "$INPUT_ENV" = "test" ]; then
          echo "TF_VAR_saml_entity_id_url=https://test.sandbox.loginproxy.gov.bc.ca/auth/realms/"  >> $GITHUB_ENV
          echo "TF_VAR_otp_provider_url=https://test.sandbox.otp.loginproxy.gov.bc.ca" >> $GITHUB_ENV

        elif [ "$INPUT_ENV" = "prod" ]; then
          echo "TF_VAR_prod_digital_credential_url=https://vc-authn-oidc-test.apps.silver.devops.gov.bc.ca" >> $GITHUB_ENV
          echo "TF_VAR_saml_entity_id_url=https://sandbox.loginproxy.gov.bc.ca/auth/realms/"  >> $GITHUB_ENV
          echo "TF_VAR_saml_idir_override=_idir1/" >> $GITHUB_ENV
          echo "TF_VAR_saml_bceidbusiness_override=_bceidbusiness1/" >> $GITHUB_ENV
          echo "TF_VAR_saml_bceidbasicbusiness_override=_bceidbasicbusiness1/" >> $GITHUB_ENV
          echo "TF_VAR_saml_bceidbasic_override=_bceidbasic1/" >> $GITHUB_ENV
          echo "TF_VAR_otp_provider_url=https://sandbox.otp.loginproxy.gov.bc.ca" >> $GITHUB_ENV

        fi
        # PROJECT_SUFFIX left null for production config

    - name: Set environment to PRODUCTION
      if: ${{ inputs.staging-env == 'production' && github.ref == 'refs/heads/main' }}
      run: |
        echo "KEYCLOAK_V2_DEV_URL=https://dev.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_TEST_URL=https://test.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_PROD_URL=https://loginproxy.gov.bc.ca" >> $GITHUB_ENV

        echo "TF_S3_BUCKET=b46814-prod-keycloak" >> $GITHUB_ENV
        INPUT_ENV="${{ inputs.environment }}"
        if [ "$INPUT_ENV" = "dev" ]; then
          echo "SITEMINDER_PROJECT=TEST" >> $GITHUB_ENV
        elif [ "$INPUT_ENV" = "test" ]; then
          echo "SITEMINDER_PROJECT=TEST" >> $GITHUB_ENV
        elif [ "$INPUT_ENV" = "prod" ]; then
          echo "SITEMINDER_PROJECT=PROD" >> $GITHUB_ENV
        fi

    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5   #v2

    - name: Setup Terraform
      uses: ./.github/actions/setup-terraform
      with:
        context: ./terraform-v2/keycloak-${{inputs.environment}}
        tf-version: ${{ env.TF_VERSION }}
        tf-s3-bucket: ${{ env.TF_S3_BUCKET }}
        tf-s3-bucket-key: keycloak/gold-${{ env.UPPER_ENV }}
        tf-aws-deploy-role-arn: ${{ secrets.SSO_AWS_GH_ACTIONS_DEPLOYER }}
        kc-provider-version: 5.4.0
        kc-url: ${{ vars.KEYCLOAK_V2_URL}}
        kc-username: ${{ secrets.KEYCLOAK_V2_USERNAME }}
        kc-password: ${{ secrets.KEYCLOAK_V2_PASSWORD }}
        azureidir-tenant-id: ${{ vars.AZUREIDIR_TENANT_ID }}
        azureidir-client-id: ${{ vars.AZUREIDIR_CLIENT_ID }}
        azureidir-client-secret: ${{ secrets.AZUREIDIR_CLIENT_SECRET }}
        github-client-id: ${{ vars.IDP_GITHUB_CLIENT_ID }}
        github-client-secret: ${{ secrets.IDP_GITHUB_CLIENT_SECRET }}
        digitalcredential-client-id: ${{ vars.DIGITALCREDENTIAL_CLIENT_ID }}
        digitalcredential-client-secret: ${{ secrets.DIGITALCREDENTIAL_CLIENT_SECRET }}
        otp-client-id: ${{ vars.OTP_CLIENT_ID}}
        otp-client-secret: ${{ secrets.OTP_CLIENT_SECRET }}
        ppid-client-id: ${{ secrets.PPID_CLIENT_ID }}
        ppid-client-secret: ${{ secrets.PPID_CLIENT_SECRET }}
            #prod for prod-Production, test for sandbox and dev-Production and test-Production
        siteminder-signing-certificate: ${{ secrets[format('{0}_SITEMINDER_SIGNING_CERTIFICATE', env.SITEMINDER_PROJECT)] }}

        plan: true
        tf-modules-cache-key: ${{ steps.tf-modules.outputs.latest-sha }}
