name: Terraform V2 Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: env to deploy
        type: choice
        options: [DEV, TEST, PROD]
        default: DEV
env:
  TF_VERSION: 1.11.0

jobs:
  terraform:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: hmarr/debug-action@v2
    - name: Fail if not main or dev
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/SSOTEAM-2831'
      run: |
        echo "This workflow only runs on main or dev branches."
        exit 1

    - name: Set common variables
      run: |
        echo "DEV_AZUREIDIR_TENANT_ID=${{ secrets.DEV_AZUREIDIR_TENANT_ID }}" >> $GITHUB_ENV
        echo "TEST_AZUREIDIR_TENANT_ID=${{ secrets.TEST_AZUREIDIR_TENANT_ID }}" >> $GITHUB_ENV
        echo "PROD_AZUREIDIR_TENANT_ID=${{ secrets.PROD_AZUREIDIR_TENANT_ID }}" >> $GITHUB_ENV

    # TO BE REFACTORED WHEN THE SECRETS ARE MOVED TO OPENSHIFT
    - name: Set dev branch environment to SANDBOX
      # if: github.ref == 'refs/heads/dev'
      if: github.ref == 'refs/heads/SSOTEAM-2831'
      run: |
        echo "KEYCLOAK_V2_DEV_URL=https://dev.sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_TEST_URL=https://test.sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_PROD_URL=https://sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "PROJECT_SUFFIX=_SANDBOX" >> $GITHUB_ENV
        echo "SITEMINDER_PROJECT=TEST" >> $GITHUB_ENV
        echo "TF_S3_BUCKET=b46814-dev-keycloak" >> $GITHUB_ENV
        echo "TF_VAR_siteminder_single_sign_on_service_url=https://sfstest7.gov.bc.ca/affwebservices/public/saml2sso" >> $GITHUB_ENV
        echo "TF_VAR_github_org=bcgov-sso" >> $GITHUB_ENV


        INPUT_ENV="${{ github.event.inputs.environment }}"

        if [ "$INPUT_ENV" = "DEV" ]; then
          echo "TF_VAR_saml_entity_id_url=https://dev.sandbox.loginproxy.gov.bc.ca/auth/realms/"  >> $GITHUB_ENV
          echo "TF_VAR_otp_provider_url=https://dev.sandbox.otp.loginproxy.gov.bc.ca" >> $GITHUB_ENV
          echo "TF_VAR_ppid_api_url=https://idsit.gov.bc.ca/iis-apis/v1/ppids" >> $GITHUB_ENV
          echo "TF_VAR_ppid_token_url=https://idsit.gov.bc.ca/oauth2/token" >> $GITHUB_ENV
          echo "TF_VAR_ppid_issuer=urn:ca:bc:gov:idimwebtests:f2ac23eb-eaa5-4640-93b7-187edbda4b31" >> $GITHUB_ENV

        elif [ "$INPUT_ENV" = "TEST" ]; then
          echo "TF_VAR_saml_entity_id_url=https://test.sandbox.loginproxy.gov.bc.ca/auth/realms/"  >> $GITHUB_ENV
          echo "TF_VAR_otp_provider_url=https://test.sandbox.otp.loginproxy.gov.bc.ca" >> $GITHUB_ENV
          echo "TF_VAR_ppid_api_url=https://idsit.gov.bc.ca/iis-apis/v1/ppids" >> $GITHUB_ENV
          echo "TF_VAR_ppid_token_url=https://idsit.gov.bc.ca/oauth2/token" >> $GITHUB_ENV
          echo "TF_VAR_ppid_issuer=urn:ca:bc:gov:idimwebtests:f2ac23eb-eaa5-4640-93b7-187edbda4b31" >> $GITHUB_ENV

        elif [ "$INPUT_ENV" = "PROD" ]; then
          echo "TF_VAR_digital_credential_url=https://vc-authn-oidc-test.apps.silver.devops.gov.bc.ca" >> $GITHUB_ENV
          echo "TF_VAR_saml_entity_id_url=https://sandbox.loginproxy.gov.bc.ca/auth/realms/"  >> $GITHUB_ENV
          echo "TF_VAR_saml_idir_override=_idir1/" >> $GITHUB_ENV
          echo "TF_VAR_saml_bceidbusiness_override=_bceidbusiness1/" >> $GITHUB_ENV
          echo "TF_VAR_saml_bceidbasicbusiness_override=_bceidbasicbusiness1/" >> $GITHUB_ENV
          echo "TF_VAR_saml_bceidbasic_override=_bceidbasic1/" >> $GITHUB_ENV
          echo "TF_VAR_otp_provider_url=https://sandbox.otp.loginproxy.gov.bc.ca" >> $GITHUB_ENV
          echo "TF_VAR_ppid_api_url=https://idsit.gov.bc.ca/iis-apis/v1/ppids" >> $GITHUB_ENV
          echo "TF_VAR_ppid_token_url=https://idsit.gov.bc.ca/oauth2/token" >> $GITHUB_ENV
          echo "TF_VAR_ppid_issuer=urn:ca:bc:gov:idimwebtests:f2ac23eb-eaa5-4640-93b7-187edbda4b31" >> $GITHUB_ENV

        fi
        # PROJECT_SUFFIX left null for production config

    - name: Set main branch environment to PRODUCTION
      if: github.ref == 'refs/heads/main'
      run: |
        echo "KEYCLOAK_V2_DEV_URL=https://dev.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_TEST_URL=https://test.loginproxy.gov.bc.ca" >> $GITHUB_ENV
        echo "KEYCLOAK_V2_PROD_URL=https://loginproxy.gov.bc.ca" >> $GITHUB_ENV

        echo "TF_S3_BUCKET=b46814-prod-keycloak" >> $GITHUB_ENV
        if [ "$INPUT_ENV" = "DEV" ]; then
          echo "SITEMINDER_PROJECT=TEST" >> $GITHUB_ENV
        elif [ "$INPUT_ENV" = "TEST" ]; then
          echo "SITEMINDER_PROJECT=TEST" >> $GITHUB_ENV
        elif [ "$INPUT_ENV" = "PROD" ]; then
          echo "SITEMINDER_PROJECT=PROD" >> $GITHUB_ENV
        fi

    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: ./.github/actions/setup-terraform
      with:
      # TEMP CONTEXT FOR TESTING SET WITH VAR IF THIS WORKS
        context: ./terraform-v2/keycloak-dev
        tf-version: ${{ env.TF_VERSION }}
        tf-s3-bucket: ${{ env.TF_S3_BUCKET }}
        tf-s3-bucket-key: keycloak/gold-${{ github.event.inputs.environment }}
        tf-aws-deploy-role-arn: ${{ secrets[format('SSO_AWS_GH_ACTIONS_DEPLOYER{0}', env.PROJECT_SUFFIX)] }}
        kc-provider-version: 5.4.0


        kc-url: ${{ env[format('KEYCLOAK_V2_{0}_URL', github.event.inputs.environment)] }}
        kc-username: ${{ secrets[format('KEYCLOAK_V2_{0}_USERNAME{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        kc-password: ${{ secrets[format('KEYCLOAK_V2_{0}_PASSWORD{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        azureidir-tenant-id: ${{ env[format('{0}_AZUREIDIR_TENANT_ID', github.event.inputs.environment)] }}
        azureidir-client-id: ${{ secrets[format('{0}_AZUREIDIR_CLIENT_ID{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        azureidir-client-secret: ${{ secrets[format('{0}_AZUREIDIR_CLIENT_SECRET{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        github-client-id: ${{ secrets[format('{0}_GITHUB_CLIENT_ID{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        github-client-secret: ${{ secrets[format('{0}_GITHUB_CLIENT_SECRET{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        digitalcredential-client-id: ${{ secrets[format('{0}_DIGITALCREDENTIAL_CLIENT_ID{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        digitalcredential-client-secret: ${{ secrets[format('{0}_DIGITALCREDENTIAL_CLIENT_SECRET{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        otp-client-id: ${{ secrets[format('{0}_OTP_CLIENT_ID{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        otp-client-secret: ${{ secrets[format('{0}_OTP_CLIENT_SECRET{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        ppid-client-id: ${{ secrets[format('{0}_PPID_CLIENT_ID{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        ppid-client-secret: ${{ secrets[format('{0}_PPID_CLIENT_SECRET{1}', github.event.inputs.environment, env.PROJECT_SUFFIX)] }}
        #prod for prod-Production, test for sandbox and dev-Production and test-Production
        siteminder-signing-certificate: ${{ secrets[format('{0}_SITEMINDER_SIGNING_CERTIFICATE', env.SITEMINDER_PROJECT)] }}

        plan: true
        tf-modules-cache-key: ${{ steps.tf-modules.outputs.latest-sha }}
